#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

DIST_FILES=(
    'COPYING'					''
    'data/msgs/connected.wav'			''
    'data/msgs/disco.wav'			''
    'data/msgs/done.wav'			''
    'data/msgs/driving_up.wav'			''
    'data/msgs/op_complete.wav'			''
    'data/msgs/plan_end.wav'			''
    'data/msgs/plan_start.wav'			''
    'data/msgs/ready2conn.wav'			''
    'data/msgs/start_pb.wav'			''
    'data/msgs/start_tow.wav'			''
    'data/msgs/connected.wav'			''
    'data/msgs/disco.wav'			''
    'data/msgs/done.wav'			''
    'data/msgs/driving_up.wav'			''
    'data/msgs/op_complete.wav'			''
    'data/msgs/plan_end.wav'			''
    'data/msgs/plan_start.wav'			''
    'data/msgs/ready2conn.wav'			''
    'data/msgs/start_pb.wav'			''
    'data/msgs/start_tow.wav'			''
    'data/icons/accept_plan.png'		''
    'data/icons/delete_seg.png'			''
    'data/icons/place_seg.png'			''
    'data/icons/cancel_plan.png'		''
    'data/icons/move_view.png'			''
    'data/icons/rotate_seg.png'			''
    'objects/tugs/AST-3F.tug/AST-3F.obj'	''
    'objects/tugs/AST-3F.tug/AST-3F_tex.png'	'//PNG2DDS//'
    'objects/tugs/AST-3F.tug/air.wav'		''
    'objects/tugs/AST-3F.tug/beeper.wav'	''
    'objects/tugs/AST-3F.tug/engine.wav'	''
    'objects/tugs/AST-3F.tug/info.cfg'		''
)

function install_xtra_files() {
	for (( I=0; $I < ${#DIST_FILES[@]}; I=$I + 2 )); do
		FILE="${DIST_FILES[$I]}"
		DSTDIR="${DIST_FILES[$I+1]}"
		if [[ "$DSTDIR" = "//PNG2DDS//" ]]; then
			DSTDIR=""
			XFERCMD="convert"
			TGTFILE="$(basename "$FILE")"
			TGTFILE="${TGTFILE/%.png/.dds}"
		else
			TGTFILE="$(basename "$FILE")"
			XFERCMD="cp"
		fi
		if [[ "$DSTDIR" = "" ]]; then
			DSTDIR="$(dirname "$FILE")"
		fi
		mkdir -p "BetterPushback/$DSTDIR"
		$XFERCMD "$FILE" "BetterPushback/$DSTDIR/$TGTFILE"
	done
}

rm -rf BetterPushback

(cd zlib && ./build_zlib_deps ) || exit 1
(cd libpng && ./build_libpng_deps ) || exit 1

case `uname` in
Linux)
	set -e
	( cd qmake && ./build-win-lin )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/{win,lin}.xpl BetterPushback/32
	cp qmake/output/64/{win,lin}.xpl BetterPushback/64
	install_xtra_files
	set +e
	;;
Darwin)
	set -e
	( cd qmake && ./build-mac )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/mac.xpl BetterPushback/32
	cp qmake/output/64/mac.xpl BetterPushback/64
	install_xtra_files
	set +e
	;;
*)
	echo "Unsupported platform" >&2
	exit 1
	;;
esac
