#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

DIST_FILES=(
    'COPYING'					''
    'data/msgs/README.txt'			''
    'data/msgs/cc_aliases.cfg'			''
    'objects/tugs/LIVERIES_HOWTO.txt'		''
    'objects/night_lamp.obj'			''
)

function install_xtra_file() {
	FILE="$1"
	DSTDIR="$2"
	if [[ "$DSTDIR" = "//PNG2DDS//" ]]; then
		DSTDIR=""
		XFERCMD="convert"
		TGTFILE="$(basename "$FILE")"
		TGTFILE="${TGTFILE/%.png/.dds}"
	else
		TGTFILE="$(basename "$FILE")"
		XFERCMD="cp"
	fi
	if [[ "$DSTDIR" = "" ]]; then
		DSTDIR="$(dirname "$FILE")"
	fi
	mkdir -p "BetterPushback/$DSTDIR"
	$XFERCMD "$FILE" "BetterPushback/$DSTDIR/$TGTFILE"
}

function install_xtra_files() {
	for (( I=0; $I < ${#DIST_FILES[@]}; I=$I + 2 )); do
		install_xtra_file "${DIST_FILES[$I]}" "${DIST_FILES[$I + 1]}"
	done
}

function install_audio_files() {
	FILES=(
		'connected.opus'
		'disco.opus'
		'done_left.opus'
		'done_right.opus'
		'driving_up.opus'
		'op_complete.opus'
		'plan_end.opus'
		'plan_start.opus'
		'ready2conn.opus'
		'start_pb.opus'
		'start_tow.opus'
		'connected.opus'
		'disco.opus'
		'driving_up.opus'
		'op_complete.opus'
		'plan_end.opus'
		'plan_start.opus'
		'ready2conn.opus'
		'start_pb.opus'
		'start_tow.opus'
		'winch.opus'
	)
	find data/msgs -type f -iname '*.opus' | while read; do
		install_xtra_file "$REPLY" ""
	done
}

function install_icon_files() {
	FILES=(
		'accept_plan.png'
		'conn_first.png'
		'delete_seg.png'
		'place_seg.png'
		'cancel_plan.png'
		'move_view.png'
		'rotate_seg.png'
		'disconnect.png'
		'reconnect.png'
	)
	for DIR in data/icons/[a-z][a-z]; do
		for FILE in ${FILES[@]}; do
			install_xtra_file "$DIR/$FILE" ""
		done
	done
}

function install_tug_files() {
	FILES=( $( find objects/tugs/*.tug -type f \
	    '(' -iname '*.obj' -or -iname '*.cfg' -or -iname '*.wav' -or \
	    -iname '*.opus' -or -iname '*.png' ')' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}

function install_po_files() {
	FILES=( $( find data/po -iname '*.po' ) )
	for FILE in ${FILES[@]}; do
		install_xtra_file "$FILE" ""
	done
}

rm -rf BetterPushback

(cd pcre2 && ./build_pcre2_deps ) || exit 1
(cd libxml2 && ./build_libxml2_deps ) || exit 1

set -e

case `uname` in
Linux)
	( cd qmake && ./build-win-lin $@ )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/{win,lin}.xpl BetterPushback/32
	cp qmake/output/64/{win,lin}.xpl BetterPushback/64
	;;
Darwin)
	( cd qmake && ./build-mac $@ )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/mac.xpl BetterPushback/32
	cp qmake/output/64/mac.xpl BetterPushback/64
	;;
*)
	echo "Unsupported platform" >&2
	exit 1
	;;
esac

install_xtra_files
install_po_files
install_audio_files
install_icon_files
install_tug_files

set +e
