#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

DIST_FILES=(
    'COPYING'					''
    'data/msgs/en/connected.opus'		''
    'data/msgs/en/disco.opus'			''
    'data/msgs/en/done_left.opus'		''
    'data/msgs/en/done_right.opus'		''
    'data/msgs/en/driving_up.opus'		''
    'data/msgs/en/op_complete.opus'		''
    'data/msgs/en/plan_end.opus'		''
    'data/msgs/en/plan_start.opus'		''
    'data/msgs/en/ready2conn.opus'		''
    'data/msgs/en/start_pb.opus'		''
    'data/msgs/en/start_tow.opus'		''
    'data/msgs/en/connected.opus'		''
    'data/msgs/en/disco.opus'			''
    'data/msgs/en/driving_up.opus'		''
    'data/msgs/en/op_complete.opus'		''
    'data/msgs/en/plan_end.opus'		''
    'data/msgs/en/plan_start.opus'		''
    'data/msgs/en/ready2conn.opus'		''
    'data/msgs/en/start_pb.opus'		''
    'data/msgs/en/start_tow.opus'		''
    'data/msgs/en/winch.opus'			''
    'data/msgs/de/connected.opus'		''
    'data/msgs/de/disco.opus'			''
    'data/msgs/de/done_left.opus'		''
    'data/msgs/de/done_right.opus'		''
    'data/msgs/de/driving_up.opus'		''
    'data/msgs/de/op_complete.opus'		''
    'data/msgs/de/plan_end.opus'		''
    'data/msgs/de/plan_start.opus'		''
    'data/msgs/de/ready2conn.opus'		''
    'data/msgs/de/start_pb.opus'		''
    'data/msgs/de/start_tow.opus'		''
    'data/msgs/de/connected.opus'		''
    'data/msgs/de/disco.opus'			''
    'data/msgs/de/driving_up.opus'		''
    'data/msgs/de/op_complete.opus'		''
    'data/msgs/de/plan_end.opus'		''
    'data/msgs/de/plan_start.opus'		''
    'data/msgs/de/ready2conn.opus'		''
    'data/msgs/de/start_pb.opus'		''
    'data/msgs/de/start_tow.opus'		''
    'data/msgs/de/winch.opus'			''
    'data/msgs/ru/connected.opus'		''
    'data/msgs/ru/disco.opus'			''
    'data/msgs/ru/done_left.opus'		''
    'data/msgs/ru/done_right.opus'		''
    'data/msgs/ru/driving_up.opus'		''
    'data/msgs/ru/op_complete.opus'		''
    'data/msgs/ru/plan_end.opus'		''
    'data/msgs/ru/plan_start.opus'		''
    'data/msgs/ru/ready2conn.opus'		''
    'data/msgs/ru/start_pb.opus'		''
    'data/msgs/ru/start_tow.opus'		''
    'data/msgs/ru/connected.opus'		''
    'data/msgs/ru/disco.opus'			''
    'data/msgs/ru/driving_up.opus'		''
    'data/msgs/ru/op_complete.opus'		''
    'data/msgs/ru/plan_end.opus'		''
    'data/msgs/ru/plan_start.opus'		''
    'data/msgs/ru/ready2conn.opus'		''
    'data/msgs/ru/start_pb.opus'		''
    'data/msgs/ru/start_tow.opus'		''
    'data/msgs/ru/winch.opus'			''
    'data/icons/en/accept_plan.png'		''
    'data/icons/en/conn_first.png'		''
    'data/icons/en/delete_seg.png'		''
    'data/icons/en/place_seg.png'		''
    'data/icons/en/cancel_plan.png'		''
    'data/icons/en/move_view.png'		''
    'data/icons/en/rotate_seg.png'		''
    'data/icons/de/accept_plan.png'		''
    'data/icons/de/conn_first.png'		''
    'data/icons/de/delete_seg.png'		''
    'data/icons/de/place_seg.png'		''
    'data/icons/de/cancel_plan.png'		''
    'data/icons/de/move_view.png'		''
    'data/icons/de/rotate_seg.png'		''
    'data/icons/fr/accept_plan.png'		''
    'data/icons/fr/conn_first.png'		''
    'data/icons/fr/delete_seg.png'		''
    'data/icons/fr/place_seg.png'		''
    'data/icons/fr/cancel_plan.png'		''
    'data/icons/fr/move_view.png'		''
    'data/icons/fr/rotate_seg.png'		''
    'data/icons/ru/accept_plan.png'		''
    'data/icons/ru/conn_first.png'		''
    'data/icons/ru/delete_seg.png'		''
    'data/icons/ru/place_seg.png'		''
    'data/icons/ru/cancel_plan.png'		''
    'data/icons/ru/move_view.png'		''
    'data/icons/ru/rotate_seg.png'		''
    'data/po/de/strings.po'			''
    'data/po/ru/strings.po'			''
    'objects/tugs/AST-3F.tug/AST-3F.obj'	''
    'objects/tugs/AST-3F.tug/air.wav'		''
    'objects/tugs/AST-3F.tug/beeper.wav'	''
    'objects/tugs/AST-3F.tug/engine.wav'	''
    'objects/tugs/AST-3F.tug/info.cfg'		''
    'objects/tugs/AST-3F.tug/liveries/generic.livery/AST-3F_tex.png' \
	'//PNG2DDS//'
    'objects/tugs/AST-3F.tug/liveries/generic.livery/AST-3F_lit.png' \
	'//PNG2DDS//'
    'objects/tugs/AST-3F.tug/liveries/GlobeGroundBerlin.livery/info.cfg' \
	''
    'objects/tugs/AST-3F.tug/liveries/GlobeGroundBerlin.livery/AST-3F_tex.png' \
	'//PNG2DDS//'
    'objects/tugs/AST-3F.tug/liveries/HAviationGroundServices.livery/info.cfg' \
	''
    'objects/tugs/AST-3F.tug/liveries/HAviationGroundServices.livery/AST-3F_tex.png' \
	'//PNG2DDS//'
    'objects/tugs/AST-3F.tug/liveries/LEOS.livery/info.cfg'	''
    'objects/tugs/AST-3F.tug/liveries/LEOS.livery/AST-3F_tex.png' '//PNG2DDS//'
    'objects/tugs/AST-3F.tug/liveries/Swissport.livery/info.cfg'	''
    'objects/tugs/AST-3F.tug/liveries/Swissport.livery/AST-3F_tex.png' \
	'//PNG2DDS//'
    'objects/tugs/AST-1X.tug/AST-1X.obj'	''
    'objects/tugs/AST-1X.tug/beeper.wav'	''
    'objects/tugs/AST-1X.tug/engine.wav'	''
    'objects/tugs/AST-1X.tug/info.cfg'		''
    'objects/tugs/AST-1X.tug/liveries/generic.livery/AST-1X_tex.png' \
	'//PNG2DDS//'
    'objects/tugs/AP88.tug/AP88.obj'		''
    'objects/tugs/AP88.tug/engine.wav'		''
    'objects/tugs/AP88.tug/info.cfg'		''
    'objects/tugs/AP88.tug/liveries/generic.livery/AAP88_tex.png' \
	'//PNG2DDS//'
)

function install_xtra_files() {
	for (( I=0; $I < ${#DIST_FILES[@]}; I=$I + 2 )); do
		FILE="${DIST_FILES[$I]}"
		DSTDIR="${DIST_FILES[$I+1]}"
		if [[ "$DSTDIR" = "//PNG2DDS//" ]]; then
			DSTDIR=""
			XFERCMD="convert"
			TGTFILE="$(basename "$FILE")"
			TGTFILE="${TGTFILE/%.png/.dds}"
		else
			TGTFILE="$(basename "$FILE")"
			XFERCMD="cp"
		fi
		if [[ "$DSTDIR" = "" ]]; then
			DSTDIR="$(dirname "$FILE")"
		fi
		mkdir -p "BetterPushback/$DSTDIR"
		$XFERCMD "$FILE" "BetterPushback/$DSTDIR/$TGTFILE"
	done
}

rm -rf BetterPushback

(cd zlib && ./build_zlib_deps ) || exit 1
(cd libpng && ./build_libpng_deps ) || exit 1
(cd pcre2 && ./build_pcre2_deps ) || exit 1
(cd libxml2 && ./build_libxml2_deps ) || exit 1

case `uname` in
Linux)
	set -e
	( cd qmake && ./build-win-lin )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/{win,lin}.xpl BetterPushback/32
	cp qmake/output/64/{win,lin}.xpl BetterPushback/64
	install_xtra_files
	set +e
	;;
Darwin)
	set -e
	( cd qmake && ./build-mac )
	mkdir -p BetterPushback/{32,64}
	cp qmake/output/32/mac.xpl BetterPushback/32
	cp qmake/output/64/mac.xpl BetterPushback/64
	install_xtra_files
	set +e
	;;
*)
	echo "Unsupported platform" >&2
	exit 1
	;;
esac
