#!/bin/sh

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build BetterPushback for both Windows and Linux,
# 32- & 64-bit flavors. Install the necessary mingw cross-compile utilities
# first.
# On Linux also do "apt install libopenal-dev:x86_64 libopenal-dev:i386".

# Locate libacfutils and build it if necessary
LIBACFUTILS="$(qmake -query LIBACFUTILS)"

release_dir="debug"

if [ "$LIBACFUTILS" = "**Unknown**" ]; then
	echo "Please use \"qmake -set LIBACFUTILS <<path>>\" to " \
	    "point to where you have libacfutils unpacked." >&2
	exit 1
fi

if ! [ -f "$LIBACFUTILS/qmake/win32/libacfutils.a" ] ||
    ! [ -f "$LIBACFUTILS/qmake/win64/libacfutils.a" ] ||
    ! [ -f "$LIBACFUTILS/qmake/lin32/libacfutils.a" ] ||
    ! [ -f "$LIBACFUTILS/qmake/lin64/libacfutils.a" ]; then
	if ! ( cd "$LIBACFUTILS/qmake" && ./build-win-lin ) ; then
		exit 1
	fi
fi

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(grep 'processor[[:space:]]\+:' /proc/cpuinfo  | wc -l) + 1 ))

rm -rf "$release_dir" output
mkdir -p output/32 output/64

make distclean > /dev/null
qmake -set CROSS_COMPILE x86_64-w64-mingw32- && \
    qmake -spec win32-g++ && \
    make -j $NCPUS && \
    mv "$release_dir/win.xpl1.dll" output/64/win.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean > /dev/null
qmake -set CROSS_COMPILE i686-w64-mingw32- && \
    qmake -spec win32-g++ && \
    make -j $NCPUS && \
    mv "$release_dir/win.xpl1.dll" output/32/win.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean > /dev/null

qmake -spec linux-g++-64 && \
    make -j $NCPUS && \
    mv liblin.xpl.so output/64/lin.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean > /dev/null
qmake -spec linux-g++-32 && \
    make -j $NCPUS && \
    mv liblin.xpl.so output/32/lin.xpl
if [ $? != 0 ] ; then
  exit
fi

make distclean > /dev/null
