#!/bin/sh

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build BetterPushback for Mac 32- & 64-bit flavors.
# Make sure also to install macports's qt5-qtcreator package and
# have `qmake' available in your $PATH.

# Locate libacfutils and build it if necessary
LIBACFUTILS="$(qmake -query LIBACFUTILS)"

if [ "$LIBACFUTILS" = "**Unknown**" ]; then
	echo "Please use \"qmake -set LIBACFUTILS <<path>>\" to " \
	    "point to where you have libacfutils unpacked." >&2
	exit 1
fi

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(sysctl -n hw.ncpu) + 1 ))

rm -rf output
mkdir -p output/64

make distclean > /dev/null
qmake -spec macx-clang && \
    make -j $NCPUS && \
    mv libmac.xpl.dylib output/64/mac.xpl
if [ $? != 0 ] ; then
  exit
fi
